### PR TITLE
Raincrash: added feed-gsoc xml

### PR DESCRIPTION
**Pull request by raincrash**
*Please check the following things before sending your pull request:*
- [x] Verify that the url is a valid feed (and not a link to your blog).
- [x] Verify that the feed only contains blog posts relating to GSoC. (i.e. if you have a personal blog, you have added the feed for the tag/label that will only have posts relating to GSoC. Refer the README)
- [x] Add some info about you in the pull request.

### CODE REVIEW

**Comment by raincrash** [comment]
@ajinkya007 @rhnvrm Is the planetGSoC project active?

**Comment by rhnvrm** [comment]
@raincrash - I was managing deployment and merge requests last year. Would be great to have a set of new volunteers for GSoC 2017.

**Comment by raincrash** [comment]
@rhnvrm Sure! I can volunteer. 👍

**Comment by rhnvrm** [comment]
@raincrash Great! Have added you to the @planetGSoC/volunteers team!

**Comment by i338395** [comment]
Hey @rhnvrm Thanks for adding me, could you auth me the write access? So I can merge PRs.

**Pull request merged**
