### PR TITLE
Add Hatim's GSoC blog feed

### PR DESCRIPTION
**Pull request by hatimak**
*Please check the following things before sending your pull request:*
- [x] Verify that the url is a valid feed (and not a link to your blog).
- [x] Verify that the feed only contains blog posts relating to GSoC. (i.e. if you have a personal blog, you have added the feed for the tag/label that will only have posts relating to GSoC. Refer the README)
- [x] Add some info about you in the pull request.

### CODE REVIEW

**Comment by hatimak** [comment]
I am a GSoC 2017 student with FOSSi and my project is to replicate the EDSAC on an FPGA. I am currently a Bachelors student in Electrical Engineering at the Indian Institute of Technology Patna. 
Please read more about the project [here](https://summerofcode.withgoogle.com/projects/#4908318351949824). You can have a look at my proposal [here](https://goo.gl/3q0uKa).

**Comment by raincrash** [comment]
Make sure there aren't any conflicts. I'll merge. @hatimak

**Comment by hatimak** [comment]
No conflicts, please merge. :)

**Comment by hatimak** [comment]
@raincrash conflicts resolved 👍  please merge 😄

**Pull request merged**
