### PR TITLE
Updated gsoc.txt

### PR DESCRIPTION
**Pull request by Srijancse**
Added my blog address (http://srijanfoss2k16.blogspot.in/search/label/Wikitolearn)

### CODE REVIEW

**Comment by rhnvrm** [comment]
Hello! Thanks for sending your pull request.

Before I merge, can you please fix your feed URL?

Suppose your label is named "GSoC" then the feed for that specific tag will reside in blog.com/feeds/posts/default/-/GSoC/?alt=rss. You can then add this to list/gsoc.txt in a new line.

**Comment by rhnvrm** [comment]
Your correct feed is at: http://srijanfoss2k16.blogspot.in/feeds/posts/default/-/GSoC/

Can you please fix this?

**Comment by Srijancse** [comment]
Sure! :)

**Comment by rhnvrm** [comment]
Merged! :+1:

**Pull request merged**
